name: Convert Scripts

on:
  push:
    paths:
      - 'QuantumultX/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
          npm install --save @types/node fs-extra axios
          npm install --save-dev @types/fs-extra

      - name: Clean output directories
        run: |
          rm -rf Loon
          rm -rf Surge
          mkdir -p Loon/plugins
          mkdir -p Surge/modules

      - name: Run conversion script
        id: convert
        run: |
          ts-node scripts/convert.ts

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for changes
        id: check_changes
        run: |
          git add Loon/ Surge/
          # 检查是否有实际变化
          if git diff --staged --quiet; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -m "Auto convert scripts: $(date +'%Y-%m-%d %H:%M:%S')"
          git fetch origin
          git pull origin main --no-rebase
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}