name: Convert Scripts

on:
  push:
    paths:
      - 'QuantumultX/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}  # Limits to one run per branch/workflow
      cancel-in-progress: true  # Cancels older runs if a new one starts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for reliable pulls

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
          npm install --save @types/node fs-extra axios
          npm install --save-dev @types/fs-extra

      - name: Clean output directories
        run: |
          rm -rf Loon
          rm -rf Surge
          mkdir -p Loon/plugins
          mkdir -p Surge/modules

      - name: Run conversion script
        run: |
          ts-node scripts/convert.ts

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add Loon/ Surge/
          git commit -m "Auto convert scripts: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git fetch origin
          git pull origin main --no-rebase  # Merge strategy to handle remote changes
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}