name: Convert Scripts

on:
  push:
    paths:
      - 'QuantumultX/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
          npm install --save @types/node fs-extra axios
          npm install --save-dev @types/fs-extra

      - name: Clean output directories
        run: |
          rm -rf Loon
          rm -rf Surge
          mkdir -p Loon/plugins
          mkdir -p Surge/modules

      - name: Run conversion script
        run: |
          ts-node scripts/convert.ts

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add Loon/ Surge/
          git commit -m "Auto convert scripts: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          # Debug: Show current branch and remote state
          git fetch origin
          git log --oneline --graph --all -n 5
          # Pull with merge (instead of rebase) to handle conflicts safely
          git pull origin main --no-rebase || echo "Pull failed, proceeding with local changes"
          # Push the result
          git push origin main || echo "Git push failed"
        shell: bash

      - name: Debug Git Push
        if: failure()
        run: |
          echo "Debugging Git Push failure"
          git status
          git remote -v
          git config -l
          git show-ref
        shell: bash